# skills/screen_vision.py
from skills.os_control import take_screenshot
from pathlib import Path


def capture_and_describe() -> tuple[str, str]:
    """
    Take screenshot and return (filepath, description_prompt).
    The description is generated by the brain using vision.
    """
    filepath = take_screenshot()
    if not filepath:
        return "", "I was unable to capture the screen, Sir."
    return filepath, ""


def get_screen_context() -> str:
    """Get what's currently on screen as context for Friday."""
    try:
        import PIL.ImageGrab as ImageGrab
        import PIL.Image as Image
        img = ImageGrab.grab()
        # Get dominant colors and basic info
        width, height = img.size
        return f"Screen resolution: {width}x{height}"
    except Exception as e:
        return f"Screen capture unavailable: {e}"
